### ISSUE TITLE
App crashes on login attempt with no info

### ISSUE THREAD

**Issue by barmfield** [jkon1513/ASE2018#34]
On emulator using Nexus 5X API 28
Steps to reproduce:
1. open app
2. leave email and password blank
3. click Login

**Comment by Lord-Left** [comment]
I can confirm that the app crashes in the emulator under these conditions.

**Comment by Lord-Left** [comment]
This issue is now resolved; both fields will prompt the user for input if login is pressed with empty username/pw fields.
