### ISSUE TITLE
Crash After Multiple Failed Signup Attempts

### ISSUE THREAD

**Issue by Luigi-PastorePica** [jkon1513/ASE2018#46]
After multiple signup attempts with invalid e-mail or password, finally providing valid entries makes the app crash. Despite this, the user is still created on the database and login works well afterwards.

**Comment by jkon1513** [comment]
i will look into this

**Comment by jkon1513** [comment]
after numerous attempts to recreate this issue by numerous different people we are convinced this issue was not caused by the app.
